name: Update stats images

on:
  # At hour 0 and 12 - aka twice a day (UTC)
  schedule:
    - cron: "0 0,12 * * *"

  # Manual trigger
  workflow_dispatch:

jobs:
  update:
    name: Update stats images
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup git
        run: |
          git config --local user.name github-actions[bot]
          git config --local user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Download stats images
        run: |
          [ ! -d img ] && mkdir img
          for stats_type in stats langs; do
            for stats_theme in default chartreuse-dark; do
              echo "Downloading img/${stats_type}_${stats_theme}.svg"
              GIT_ADD=
              if [[ ${stats_type} == 'stats' ]]; then
                curl -sS -o img/${stats_type}_${stats_theme}.svg "https://github-readme-stats.vercel.app/api?username=bittor7x0&include_all_commits=true&count_private=true&show_icons=true&hide=stars&hide_border=true&disable_animations=true&line_height=29&theme=${stats_theme}"
                [[ $(grep '</svg>' img/${stats_type}_${stats_theme}.svg) && ! $(grep -A1 'data-testid="commits"' img/${stats_type}_${stats_theme}.svg | grep '>0</text>') ]] && GIT_ADD=1
              elif [[ ${stats_type} == 'langs' ]]; then
                curl -sS -o img/${stats_type}_${stats_theme}.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=bittor7x0&layout=compact&hide_border=true&langs_count=8&hide=TeX,Smarty,Roff,CSS&disable_animations=true&line_height=28&theme=${stats_theme}"
                [[ $(grep '</svg>' img/${stats_type}_${stats_theme}.svg) ]] && GIT_ADD=1
              fi
              if [[ -n ${GIT_ADD} ]]; then
                git add img/${stats_type}_${stats_theme}.svg
              else
                echo "Error: the file img/${stats_type}_${stats_theme}.svg is incorrect. Check content:"
                cat img/${stats_type}_${stats_theme}.svg
              fi
            done
          done

      - name: Git status
        run: |
          GIT_DIFF=$(git status --short -uno | grep -e '^[MAD]' || :)
          if [ -n "${GIT_DIFF}" ]; then echo "GIT_COMMIT=1" >> ${GITHUB_ENV}; fi

      - name: Git commit
        if: env.GIT_COMMIT
        run: |
          git commit -qm "chore: update stats images"
          git show --stat-count=10 HEAD

      - name: Git push
        if: env.GIT_COMMIT
        run: git push origin main
